version: '3.3'

services:
  python:
    build:
      context: .
    volumes:
      - ".:/workspaces"
    ports:
      - "18888:8888"
    command: "jupyter notebook --port 8888 --ip=0.0.0.0 --notebook-dir=/workspaces --no-browser --allow-root --NotebookApp.token=''"
